name: RuhurKulturErlbnisApp
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.0.0  <4.4.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: 0.13.6
  assets_audio_player: ^3.1.1 
  awesome_notifications: ^0.8.2
  path_provider: ^2.1.1
  geolocator: ^10.1.0
  permission_handler: ^11.0.0
  flutter_settings_ui: ^2.0.1
  provider: ^6.0.5
  url_launcher: ^6.1.14
  nb_utils: ^6.0.4


  material3_layout: ^0.0.7
  json_api: ^6.0.1
  http_interop: ^0.8.0
  firebase_core: ^2.17.0
  flutterfire_ui: ^0.4.3+20
  firebase_messaging: ^14.6.9
  upgrade: ^0.0.8
  firebase_auth: ^4.10.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/version/version.json
