// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAYjNV7O7tGAzOYeDP0N6YtoL7Q3pG520',
    appId: '1:1012358424311:web:cbaed9dc53544d4b7515f2',
    messagingSenderId: '1012358424311',
    projectId: 'filmprojekt1-44315',
    authDomain: 'filmprojekt1-44315.firebaseapp.com',
    storageBucket: 'filmprojekt1-44315.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLAPKkO7Y4gul_CQeSh0qh-0qeZU-KdtY',
    appId: '1:1012358424311:android:ea82549a56d49cfe7515f2',
    messagingSenderId: '1012358424311',
    projectId: 'filmprojekt1-44315',
    storageBucket: 'filmprojekt1-44315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6-7GSSlBZOXXH4YqzCuKg82hCT29kJTA',
    appId: '1:1012358424311:ios:59043c7548622db77515f2',
    messagingSenderId: '1012358424311',
    projectId: 'filmprojekt1-44315',
    storageBucket: 'filmprojekt1-44315.appspot.com',
    iosBundleId: 'com.example.ruhurkulturerlbnisapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6-7GSSlBZOXXH4YqzCuKg82hCT29kJTA',
    appId: '1:1012358424311:ios:007101f2ccd29ea87515f2',
    messagingSenderId: '1012358424311',
    projectId: 'filmprojekt1-44315',
    storageBucket: 'filmprojekt1-44315.appspot.com',
    iosBundleId: 'com.example.ruhurkulturerlbnisapp.RunnerTests',
  );
}
